"""upgrade channels for direct messages

Revision ID: 7c48aacb5199
Revises: 9d8c32e4f43d
Create Date: 2026-06-28 20:14:35.589733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c48aacb5199'
down_revision: Union[str, Sequence[str], None] = '9d8c32e4f43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_members',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'user_id')
    )
    op.add_column('channels', sa.Column('channel_type', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('channels', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('channels', 'guild_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('channels_guild_id_fkey'), 'channels', type_='foreignkey')
    op.create_foreign_key(None, 'channels', 'guilds', ['guild_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.create_foreign_key(op.f('channels_guild_id_fkey'), 'channels', 'guilds', ['guild_id'], ['id'])
    op.alter_column('channels', 'guild_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('channels', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('channels', 'channel_type')
    op.drop_table('channel_members')
    # ### end Alembic commands ###
